### DISCUSSION TITLE
Host Sysreptor on Kubernetes?

### DISCUSSION THREAD

**Discussion by ahmedzak97** [Syslifters/sysreptor#446] [Q&A]
I was wondering if you have a guide to deploy SysReptor on kubernetes(GKE cluster ) , if you have manifest files or a ready helm chart , that would be really useful, and expose if via k8s ingress or loadbalancer

**Comment by aronmolnar** [comment]
Hi,
This is possible. We, however, don't officially support it and haven't made such a setup.
There are some customers who did this. @mlec1 agreed to provide you some information about their setup.

**Reply by ahmedzak97** [reply]
thanks a lot

**Comment by mlec1** [comment]
Hi, we host it on kubernetes:
We have a staging env with the community edition:

[staging.txt](https://github.com/user-attachments/files/19973791/staging.txt)
Our secrets contain the following keys:

[secret-staging.txt](https://github.com/user-attachments/files/19974336/secret-staging.txt)

For the prod, we have the pro version. The only difference, we have the language tool as deployment too.

[prod.txt](https://github.com/user-attachments/files/19974358/prod.txt)

Our secret contains the following keys:
[secret-prod.txt](https://github.com/user-attachments/files/19974376/secret-prod.txt)

We use an Ingress to access the services. We have currently Traefik as Ingress Controller, but you can the one of your choice. We will switch to Gateways a bit later when [InGate](https://github.com/kubernetes-sigs/ingate) is getting more popular and mature. 

The database is based on the Zalando Operator: https://github.com/zalando/postgres-operator
We have planned to switch to the Cloud Native Postgres Operator later. 

When I have time, I want to create a helm chart from scratch based on our current Manifest files. But didn't have time so far.

**Reply by ahmedzak97** [reply]
thank you so much

**Reply by mlec1** [reply]
Hi @ahmedzak97, 

I noticed that recently on our sysreptor instance, the periodic tasks were not triggered.
I opened the ticket https://github.com/Syslifters/sysreptor/issues/531 and it turns out, we were missing a `readinessProbe` in our manifest to trigger the periodic tasks:

I tried to adapt the healthcheck from the docker compose file https://github.com/Syslifters/sysreptor/blob/8e934869a5c1022636fbcd779f70bfbc4d520fd7/deploy/sysreptor/docker-compose.yml#L64 

Which gives me that

```
          readinessProbe:
            exec:
              command:
                - curl
                - '-f'
                - http://localhost:8000/api/public/utils/healthcheck/
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 5
```

Just wanted to let you know in case you don't have it either.
