### DISCUSSION TITLE
Variable in class help.

### DISCUSSION THREAD

**Discussion by Phosvan** [Syslifters/sysreptor#452] [Q&A] [answered]
Hello, not sure exactly where to ask this. 

So basically I'm having an issue with a variable in the class section of a div.

The non working code/class is as follows - 
```html
<div id= "header-left" class="threat-tag threat-{{ report.Risk_level.label }}" >
Threat Level: {{ report.Risk_level.value }}
</div>
```

```CSS
.threat-Info {
  background-color: #0096FF !important;
}

.threat-tag {

  float: right;
  border: none;
  color: black;
  padding: 10px 20px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  margin: 4px 2px;

  border-radius: 16px;
}
```
the value of report.Risk_level is  { "value": "Info", "label": "Info" } | ergo {{ report.Risk_level.value }} -> Info
However, when replaced with 

```html
<div id= "header-left" class="threat-tag threat-Info" >
Threat Level: {{ report.Risk_level.value }}
</div>
```

The class is being applied as desired. I have tried a lot of stuff, and just cant seem to get anything to work. I feel like it can be done, I'm just not sure how. Let me know if you need anymore information. Thank you in advance, van
