### ISSUE TITLE
How to access Sysreptor outside of localhost?

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#191]
Hi,

Pardon the newb question, but I've got Sysreptor deployed in a 192.168.1.x network.  If I access Sysreptor from the system it's running on, the Web interface pops up fine.  If I try to access Sysreptor remotely from any other system on the network, it doesn't load.  Do I need to run a Web server to access the interface from another system, and/or are their variables I can set within the Docker config to make this happen?

Thanks,
Brian

**Comment by 7MinSec** [comment]
Ok I might've fixed this but let me know if this is a bad way to go.  I followed your [instructions to setup a webserver](https://docs.sysreptor.com/setup/webserver/) but instead of setting it up with an external domain.com, I followed Caddy's [instructions](https://caddyserver.com/docs/quick-starts/reverse-proxy) on making a quick and dirty reverse proxy by altering the `command` statement:

```
command: caddy reverse-proxy --from :7777 --to :8000
```
Then I did:
```
sudo docker compose up -d
```

Now when I hit http://sysreptor:7777 it loads the Web interface.

Here's the full `docker-compose.yml' file

```
version: '3.9'
name: caddy

services:
  caddy:
    image: caddy:latest
    container_name: 'sysreptor-caddy'
    restart: unless-stopped
    command: caddy reverse-proxy --from :7777 --to :8000
    volumes:
    - type: volume
      source: sysreptor-caddy-data
      target: /data
    network_mode: "host"

volumes:
  sysreptor-caddy-data:
    name: sysreptor-caddy-data
```

**Comment by aronmolnar** [comment]
This should work, just that you will have no https.

**Comment by StephanPillhofer** [comment]
You could also change the binding from `127.0.0.1` to `0.0.0.0` in the docker-compose file and restart your containers:

```
...

app:
    build: 
      context: ../
      target: api
      args: 
        VERSION: ${SYSREPTOR_VERSION}
        CA_CERTIFICATES: ${SYSREPTOR_CA_CERTIFICATES-}
    container_name: 'sysreptor-app'
    init: true
    volumes:
      - type: volume
        source: app-data
        target: /data
    expose:
      - 8000
    ports:
      - ${BIND_PORT:-0.0.0.0:8000:8000}
...

```
