### ISSUE TITLE
HTB CPTS Report Template Layout Issue

### ISSUE THREAD

**Issue by kmahyyg** [Syslifters/sysreptor#203]
In 2024.8, It seems only "Flag Discovered" page when trying to publish a pdf report, may render a table with `overflow-x`.

![20240130-014010-Google Chrome-007848@2x](https://github.com/Syslifters/sysreptor/assets/16604643/6a9e7505-770e-4565-a382-10ff37da1687)

(This template is imported about a month ago, please let me know if there's a known issue.)

The expected result should be:

![20240130-014321-Google Chrome-007850@2x](https://github.com/Syslifters/sysreptor/assets/16604643/60e5e646-2416-45c5-9c8d-8233718bf32c)

I patched this by customizing the template using a workaround, but I'm not a frontend engineer, so this may be not that perfect:

```css
/* Table styling */
table, th, td {
  border: 1px solid white;

  /* WORKAROUND: Add lines below */
  word-wrap: break-word;
  table-layout: fixed;
  overflow-wrap: break-word;
}
```
