### ISSUE TITLE
Bullet point space

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#25]
Hi there, how could I use CSS to make the space between the bullet point and the text bigger?

![Opera-2023-05-12 at 19 05 24@2x](https://github.com/Syslifters/sysreptor/assets/3596242/7f36d121-d771-449f-9ee7-3c5198751a03)

The text should still align vertically.

**Comment by vysecurity** [comment]
Turns out not easily done. You have to wrap it <li><span>texthere</span></li>

So if "*" translates to .markdown li, it won't have the span tag and it'll fail.

**Comment by MWedl** [comment]
Currently there is a bug in WeasyPrint (HTML to PDF rendering library) that some CSS rules for styling list markers are not supported correctly. But I found a workaround to add more space between the list marker and text: You can set a custom marker with spaces after it. 
```css
li::marker {
    list-style-type: "\2022    ";
}
```

**Comment by vysecurity** [comment]
Nice!

**Comment by vysecurity** [comment]
Any idea how I can do it also with:

1.
2.
3.

I want to have the text a bit spaced after the 1.2.3.

**Comment by MWedl** [comment]
You are right. I did not look at the ToC :) 
Following rules should work for bullet and numbered lists and not break ToC.
```css
ul > li {
    list-style: "\2022    ";
}
ol > li::marker {
    content: counter(list-item) ".   \200b";
}
```
