### ISSUE TITLE
Header Issues // Vue Utilization

### ISSUE THREAD

**Issue by kgdiem** [Syslifters/sysreptor#279]
We have a couple of requirements for the page headers in our report that I'm having trouble achieving in Sysreptor:

1. Dynamic content in running headers 
2. Dynamic styles in running headers

I think these could be achieved with some access to the underlying Vue component.

```
<div id="header">
  <div class="page-header">
    <div class="header-wrapper flex flex-col">
      <div class="flex justify-end">
        <img src="/assets/name/logoheader.png"/>
      </div>

      <div class="title-wrapper">
        <div class="title-container">
          <h1></h1> <!-- Dynamic, per page header -->
        </div>
      </div>
    </div>
  </div>
</div>
```

I have one additional issue, related to the header. We have the report laid out using a `<section/>` tag. When a given section overflows one page, it overflows the header on the next page. 

Example page:
```
<section id="table-of-contents" data-title="Table of Contents">
  <div class="page-cover-background">
    <img class="page-cover-background-img" src="/assets/name/X-Background.png" alt="">
  </div>

  <table-of-contents id="toc" v-slot="tocItems">
    <ul>
      <li v-for="item in tocItems" :class="'toc-level' + item.level">
        <ref :to="item.id" />
      </li>
    </ul>
  </table-of-contents>

  <pagebreak />
</section>
```

Section + page base styling:
```
@page {
    size: A4 portrait;
    margin: 0mm 0mm 0mm;
}

section {
    margin: 25mm 10mm 10mm;
}
```

Any advice on how to better utilize vue to achieve the header we'd like and how target the page in such a way that the header does not display over the content is appreciated.

**Comment by MWedl** [comment]
Hi,
dynamic content in running headers is quite limited. In SysReptor Vue is used as a preprocessor that outputs HTML. PDF generation with page splitting, adding headers, etc. is performed at a later stage in the rendering pipeline. Because of that Vue cannot directly be used to render dynamic header content that differs per page.

However, it is possible to use a limited set of dynamic elements and styles in running headers via native print CSS rules. For example you could use CSS `string-set` to define variables in pages and use these variables in the header. For example following example adds the current chapter's title to the header:
```html
<div id="header" data-sysreptor-generated="page-header">
    <div id="header-left">
        <strong class="header-title" />
    </div>
</div>
```
```css
/* Running header */
@page {
    margin-top: 35mm;

    @top-left {
        content: element(header-left);
    }
}
#header { position: absolute; width: 0; }
#header-left { position: running(header-left); }

/* Chapter title in header */
h1 {
    string-set: header-title content();
}
.header-title::before {
    content: string(header-title);
}
```

It is possible to use different headers for different areas of your report (e.g. cover page, findings list, appendix, etc.). This can be achieved by using CSS named pages. Each named page can define its own header element.
```html
<section id="page-header1">...</section/>
<section id="page-header2">...</section/>
```
```css
#page-header1 { page: page-header1; }
@page page-header1 {
    @top-left { content: running(header1); }
}

#page-header2 { page: page-header2; }
@page page-header1 {
    @top-left { content: running(header2); }
}

/* Default header */
@page {
  @top-left { content: running(header-default); }
}
```

> I have one additional issue, related to the header. We have the report laid out using a <section/> tag. When a given section overflows one page, it overflows the header on the next page.

The overflow happens because you removed the `@page` margins. Headers are placed in pages top margin area. If you want to use different margins for different areas of the document, we recommend to named pages with margins in `@page` rules instead of margins in `section` tags.
