### ISSUE TITLE
Can <figcaption> be styled?

### ISSUE THREAD

**Issue by 7MinSec** [Syslifters/sysreptor#313]
Hi,

Just curious if captions within `<figcaption>` could be stylized?  Maybe it would break HTML, but I typically like to italicize AD system names or usernames - ideally something like:

```
<figure style="border: 1px solid #0099dc;">
  <img src="/images/name/image-.png">
  <figcaption>The *LOWPRIV* user has local administrator on 777 machines</figcaption>
</figure>
```

However, in the report, *LOWPRIV* actually shows up literally with the asterisks around it, not italicized.

**Comment by MWedl** [comment]
Hi,
it is not possible to use markdown in a HTML block. This is a limitation of the CommonMark specification.

Here are some suggestions how you can style `<figcaption>` anyway:

Use markdown syntax
```md
![The *LOWPRIV* user](/images/name/image-.png){.figure-border}
```
This has the limitation, that CSS classes and styles are applied to the `<img>` tag, not to the `<figure>` tag. When all figures should have borders, you could define a CSS rule in the design.
```css
/* always add borders to figures */
.markdown figure {
  border: 1px solid #0099dc;
}
```
Or define a CSS class `.figure-border` to selectively apply borders to figures.
```css
figure:has(img.figure-border) {
    border: 2px solid #0099dc;
}
```

If you want different borders for each figure, you have to fall back to HTML with `style` attributes and use `<em>` to italicize text in HTML blocks. 
```html
<figcaption>The <em>LOWPRIV</em> user has local administrator on 777 machines</figcaption>
```
