### ISSUE TITLE
Documentation for usage of images in designs

### ISSUE THREAD

**Issue by bjoern-js** [Syslifters/sysreptor#336]
Hey, 

I am currently trying to show images for list items. However, I cannot find the correct path to the uploaded asset. 
There is also nothing in the documentation about this subject. Including the asset images in the HTML+Vue section of the PDF designer works fine for me. However, not from the CSS section.

What is the correct path to reference any image within the CSS file of a design?

```css
ul{
list-style-image: url("????");
}

//or 

li::before{
  content: '';
  display: inline-block;
  height: 10px;
  width: 10px;
  background: url("???");
}
```

**Comment by bjoern-js** [comment]
Actually, the issue was on my side after all (copy paste error):

The correct solution is to use the full path as shown in the assets section. 

To change a list item image the following can be done

```css
li::before{
  content: '';
  display: inline-block;
  height: 16px;
  width: 16px;
  background: url("/assets/name/MYIMAGE.png");
  background-size: contain;
  background-repeat: no-repeat;
}
```
