### ISSUE TITLE
Rendering issues, possibly related to PDF anti aliasing?

### ISSUE THREAD

**Issue by reggers1** [Syslifters/sysreptor#342]
This jsfiddle shows what it should look like: [fiddle](https://jsfiddle.net/L8ed5hpb/1/)

And this is what it actually looks like:
![image](https://github.com/user-attachments/assets/1cc40d49-9197-440f-af78-6e894b660e09)

As you can see, I have small white borders surrounding my objects. I used a table before, put border-spacing to 0 and border-collapse to collapse and it did not work. Switched to divs, but the issue is persistent.
I already tried colored borders to trick it, but then I get single "pixels" (1-2) on border columns and rows that extend beyond where they are supposed to be, so that is not an option either and that's also why I think this might be related to some anti aliasing.
Is there anything I can do here to remove the thin white lines?

**Comment by MWedl** [comment]
Hi,
we observed that the anti-aliasing problem comes from the PDF.js viewer used in the PDF preview. It sometimes (at certain zoom levels) displays gaps between consecutive areas. Other PDF viewers (e.g. Adobe) do not seem to have this problem.

The solution is to make the areas overlap. This can for example be achieved via coloring `td::before` pseudo-elements

```html
<table class="table-overlap">
    <thead>
        <tr>...</tr>
    </thead>
    <tbody>
        <tr>
            <td class="table-cell-overlap" :class="'risk-bg-' + finding.cvss.level">CVSS ({{ finding.cvss.score }})</td>
            <td>CVSS Vector</td>
        </tr>
        <tr>
            <td class="table-cell-overlap" :class="'risk-bg-' + finding.cvss.level">{{ finding.cvss.level }}</td>
            <td>{{ finding.cvss.vector }}</td>
        </tr>
    </tbody>
</table>
```

```css
.table-cell-overlap {
    position: relative;
}
.table-cell-overlap::before {
    content: '';
    display: block;
    position: absolute;
    width: 100%;
    height: 2px;
    top: -1px;
    left: 0;
    z-index: -1;
}
.risk-bg-critical.table-cell-overlap::before { background-color: var(--color-risk-critical); }
.risk-bg-high.table-cell-overlap::before { background-color: var(--color-risk-high); }
.risk-bg-medium.table-cell-overlap::before { background-color: var(--color-risk-medium); }
.risk-bg-low.table-cell-overlap::before { background-color: var(--color-risk-low); }
.risk-bg-info.table-cell-overlap::before { background-color: var(--color-risk-info); }
```
