### ISSUE TITLE
[Feature Request] Linenumbers for codeblocks

### ISSUE THREAD

**Issue by Lednerb** [Syslifters/sysreptor#419]
It would be a great addition to have automatic line numbering for code blocks available.

An optional syntax to enable it like adding an `=` to the language descriptor would be great, like in this example:
https://hackmd.io/EQrGZM7-Qz6xIFZiTZav8A?both

Ideally an option to start counting at a specific value can be implemented.

Maybe via a syntax like:

```
 ```python=100
```

**Comment by MWedl** [comment]
The markdown renderer adds line numbers as HTML attribute `data-line-number` to the rendered HTML for code blocks. The line numbers are not displayed by default. In the design's CSS it is possible to display line numbers for code blocks. A line number offset cannot be configured, though.

```css
.code-block-line::before {
    content: attr(data-line-number);
    text-align: right;
    user-select: none;
    display: inline-block;
    width: 2em;
    margin-left: -1em;
    margin-right: 0.2em;
    padding-right: 0.3em;
    background-color: rgba(0, 0, 0, 0.1);
}
```
