### ISSUE TITLE
Figure Headings Reference

### ISSUE THREAD

**Issue by vysecurity** [Syslifters/sysreptor#87]
For some reason when I tried the example reference, I am getting this output instead:
![Safari-2023-08-25 at 00 47 57@2x](https://github.com/Syslifters/sysreptor/assets/3596242/e3f60f10-198c-45b6-b178-76b3f4ad7b53)

Code:

```
![SQL Injection](/assets/name/image.png){#sqli}
As you see in [](#sqli) (e.g. rendered as "Figure 3")
```

How does one make it display "Figure 6" or "Fig 6" instead of the whole text?

**Comment by Lednerb** [comment]
You can adjust this via the CSS on `figcaption::before`

https://docs.sysreptor.com/designer/figures/#figure-numbering

**Comment by vysecurity** [comment]
So that's exactly what I'm doing. I don't type in "Fig. 6" it's automatically calculated using CSS. I just want to make the [](#sqli) atuomatically write Fig. 6

**Comment by MWedl** [comment]
If your design uses the global base styles, it is possible to change the CSS Variable `--prefix-figure` to set the text that is used both for figcaptions and figure references. However, the global base styles were not available in early SysReptor versions and also not in earlier versions of the demo designs.

```css
/* Include global base styles */
@import "/assets/global/base.css";

/* Override figure prefix text */
:root {
    --prefix-figure: "Fig. " !important;
}
```

**Comment by MWedl** [comment]
If your design does not include `/assets/global/base.css`, here are the CSS rules for referencing figures. Figure references have the class `.ref-figure`. Following rules set the figure prefix, figure number and hide the figure title.

```css
/* Figure */
figcaption::before {
  content: var(--prefix-figure) counter(figure-counter) " - ";
}
.ref-figure::before {
  content: var(--prefix-figure) target-counter(attr(href), figure-counter);
}
.ref-figure > .ref-title {
  display: none;
}
```
